CREATE TABLE IF NOT EXISTS Guild (GuildID UNSIGNED BIGINT NOT NULL, GuildProperties JSON DEFAULT "{}", PRIMARY KEY (GuildID)); 
CREATE UNIQUE INDEX IF NOT EXISTS Guilds on Guild (GuildID);
CREATE TABLE IF NOT EXISTS RoleList (MemberID UNSIGNED BIGINT NOT NULL, GuildID UNSIGNED BIGINT NOT NULL, Roles JSON DEFAULT "{}", PRIMARY KEY (MemberID));
CREATE INDEX IF NOT EXISTS MemberRoles on RoleList (MemberID);