CREATE TABLE IF NOT EXISTS Guild (GuildID UNSIGNED BIGINT, GuildProperties JSON, PRIMARY KEY (GuildID)); 
CREATE UNIQUE INDEX IF NOT EXISTS Guilds on Guild (GuildID);
CREATE TABLE IF NOT EXISTS RoleList (MemberID UNSIGNED BIGINT, GuildID UNSIGNED BIGINT, Roles JSON, PRIMARY KEY (MemberID));
CREATE INDEX IF NOT EXISTS MemberRoles on RoleList (MemberID);