# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven
name: Deployment

on:
  release:
    types: [created]
#  workflow_dispatch:
#    inputs:
#      release_name:
#        description: 'Name of the release'
#        required: true
#        type: string
#      tag_name:
#        description: 'Tag to use'
#        required: true
#        type: string
#      release_notes:
#        description: 'Release body'
#        required: false
#        type: string
#      pre_release:
#        description: 'Is this a pre-release'
#        required: false
#        type: boolean
#      draft:
#        description: 'Is release a draft'
#        required: false
#        type: boolean
#      generate_release_notes:
#        description: 'Auto generate name and\or body'
#        required: false
#        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v3
    - name: Set up Maven Central Repository
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        server-id: ossrh
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD
        gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
        gpg-passphrase: MAVEN_GPG_PASSPHRASE
    - name: Build with Maven
      run: mvn clean package #-Pzip
#    - name: Creating Release
#      uses: softprops/action-gh-release@v1
#      with:
#        tag_name: ${{ github.event.inputs.tag_name }}
#        #tag_name: ${{ github.ref }}
#        name: ${{ github.event.inputs.release_name }}
#        body: ${{ github.event.inputs.release_notes }}
#        prerelease: ${{ github.event.inputs.pre_release }}
#        draft: ${{ github.event.inputs.draft }}
#        generate_release_notes: ${{ github.event.inputs.generate_release_notes }}
#        fail_on_unmatched_files: true
#        files: "/home/runner/work/Watamebot/Watamebot/target/*.zip"
    - name: Deploy with Maven
      run: mvn -B deploy -Pci-cd1
      env:
        MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
        MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
        
        
    - name: Set up GitHub Package
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        server-id: github
    - name: Publish to GitHub Packages
      run: mvn -B deploy -Pci-cd2
      env:
        GITHUB_TOKEN: ${{ github.token }}
